server {
    listen 80;
    server_name www.lottexylitol.com.vn;

    return 301 https://lottexylitol.com.vn$request_uri;
}

server {
    listen 80;
    server_name lottexylitol.com.vn;

    root /var/www;
    index index.php index.html;

    access_log /var/log/nginx/project_access.log;
    error_log /var/log/nginx/project_error.log;

    client_max_body_size 25M;

    include /etc/nginx/snippets/redirects.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/(?:.+/)?index\.php$ {
        try_files $uri =404;

        fastcgi_pass app:9000;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SERVER_PORT $server_port;

        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;

        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;

        fastcgi_connect_timeout 60;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|webp|svg|ico|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }
}
